// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/chain.proto

package chain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrankId      string `protobuf:"bytes,1,opt,name=crank_id,json=crankId,proto3" json:"crank_id,omitempty"`
	Manufacturer string `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
}

func (x *CreateChainRequest) Reset() {
	*x = CreateChainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChainRequest) ProtoMessage() {}

func (x *CreateChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChainRequest.ProtoReflect.Descriptor instead.
func (*CreateChainRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChainRequest) GetCrankId() string {
	if x != nil {
		return x.CrankId
	}
	return ""
}

func (x *CreateChainRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

type CreateChainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chain *BikeChain `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *CreateChainResponse) Reset() {
	*x = CreateChainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChainResponse) ProtoMessage() {}

func (x *CreateChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChainResponse.ProtoReflect.Descriptor instead.
func (*CreateChainResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChainResponse) GetChain() *BikeChain {
	if x != nil {
		return x.Chain
	}
	return nil
}

type BikeChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CrankId      string `protobuf:"bytes,2,opt,name=crank_id,json=crankId,proto3" json:"crank_id,omitempty"`
	Manufacturer string `protobuf:"bytes,3,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
}

func (x *BikeChain) Reset() {
	*x = BikeChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_chain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BikeChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BikeChain) ProtoMessage() {}

func (x *BikeChain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BikeChain.ProtoReflect.Descriptor instead.
func (*BikeChain) Descriptor() ([]byte, []int) {
	return file_proto_chain_proto_rawDescGZIP(), []int{2}
}

func (x *BikeChain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BikeChain) GetCrankId() string {
	if x != nil {
		return x.CrankId
	}
	return ""
}

func (x *BikeChain) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

var File_proto_chain_proto protoreflect.FileDescriptor

var file_proto_chain_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x62, 0x69, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x22, 0x53, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x72, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x69, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x2e, 0x42, 0x69, 0x6b, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x05, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x22, 0x5a, 0x0a, 0x09, 0x42, 0x69, 0x6b, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x63, 0x72, 0x61, 0x6e, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61,
	0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x32, 0x51,
	0x0a, 0x05, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x48, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x1b, 0x2e, 0x62, 0x69, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x69, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_chain_proto_rawDescOnce sync.Once
	file_proto_chain_proto_rawDescData = file_proto_chain_proto_rawDesc
)

func file_proto_chain_proto_rawDescGZIP() []byte {
	file_proto_chain_proto_rawDescOnce.Do(func() {
		file_proto_chain_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_chain_proto_rawDescData)
	})
	return file_proto_chain_proto_rawDescData
}

var file_proto_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_chain_proto_goTypes = []interface{}{
	(*CreateChainRequest)(nil),  // 0: bicycle.CreateChainRequest
	(*CreateChainResponse)(nil), // 1: bicycle.CreateChainResponse
	(*BikeChain)(nil),           // 2: bicycle.BikeChain
}
var file_proto_chain_proto_depIdxs = []int32{
	2, // 0: bicycle.CreateChainResponse.chain:type_name -> bicycle.BikeChain
	0, // 1: bicycle.Chain.CreateChain:input_type -> bicycle.CreateChainRequest
	1, // 2: bicycle.Chain.CreateChain:output_type -> bicycle.CreateChainResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chain_proto_init() }
func file_proto_chain_proto_init() {
	if File_proto_chain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_chain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateChainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_chain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BikeChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_chain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chain_proto_goTypes,
		DependencyIndexes: file_proto_chain_proto_depIdxs,
		MessageInfos:      file_proto_chain_proto_msgTypes,
	}.Build()
	File_proto_chain_proto = out.File
	file_proto_chain_proto_rawDesc = nil
	file_proto_chain_proto_goTypes = nil
	file_proto_chain_proto_depIdxs = nil
}
